### PR TITLE
fix overflow in create upload request view

### PR DESCRIPTION
**Pull request by imGok**
image

### CODE REVIEW

**Comment by imGok** [comment]
pls @huynguyennovem can you check if you can change the date format as @hoangdat wants ?

**Review by huynguyennovem — COMMENTED** [review]
/lgtm thanks!

**Review by huynguyennovem — APPROVED** [review]
/lgtm thanks!

**Review by hoangdat — APPROVED** [review]

**Comment by hoangdat** [comment]
Quite hard without reference

**Pull request merged**
