### PR TITLE
Fixed download not working from mySpace and shared space

### PR DESCRIPTION
**Pull request by KhaledNjim**
### Description
[GitLab issue](https://ci.linagora.com/linagora/lgs/linshare/products/linshare-ui-user/-/issues/1201)
#### Root cause 
  Flutter_downloader requires `saveInPublicStorage` flag to be set to true for devices with android version greater than android Q(10) to be able to save in downloads folder
#### Solution
 Set the `saveInPublicStorage` flag to `true` in  the  Flutter_Downloader call in `Download_document method`

### CODE REVIEW

**Comment by hoangdat** [comment]
please describe the root cause and your solution, hope it easier for review.

**Comment by KhaledNjim** [comment]
@hoangdat done

**Comment by hoangdat** [comment]
- [ ] try to add more video demos: 
  - with android 31
  - with android 33

**Comment by hoangdat** [comment]
- beside download with FlutterDownloader, we also have `LinShareDownloadManager` work with `Dio` to support download too, please take care of it also

**Comment by KhaledNjim** [comment]
### Android 31

https://github.com/linagora/linshare-mobile-flutter-app/assets/160496984/b7036a5b-a783-4989-9054-01c452d25168

### Android 33
  for android 33 the notification in not working(#910) but the file is downloaded  
 
https://github.com/linagora/linshare-mobile-flutter-app/assets/160496984/bb375b69-a36c-4ce5-b711-12f03ec98662

**Comment by KhaledNjim** [comment]
> * beside download with FlutterDownloader, we also have `LinShareDownloadManager` work with `Dio` to support download too, please take care of it also

  I have checked it and it works as intended

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
