### PR TITLE
Pick tablet supported

### PR DESCRIPTION
**Pull request by hoangdat**
- Tablet support for context menu, destination picker
- Edit document
- auto input https://
- preview for version

### CODE REVIEW

**Comment by huynguyennovem** [comment]
There are two commits `LA-281 Edit Document Description Domain Layer`

**Review by dab246 — COMMENTED** [review]
- Suggested `https` but still have to be entered by the user.

https://user-images.githubusercontent.com/80730648/118258486-1a2da000-b4da-11eb-8093-31a15c5fe9c2.mp4

- The loading button is a bit close to the top margin and the size is quite large.

https://user-images.githubusercontent.com/80730648/118259084-e9019f80-b4da-11eb-944b-f0217c69424d.mp4

**Comment by hoangdat** [comment]
> The loading button is a bit close to the top margin and the size is quite large.
wth

**Comment by hoangdat** [comment]
> There are two commits `LA-281 Edit Document Description Domain Layer`

it is only typo error

**Comment by hoangdat** [comment]
@datnguyenhuy please check here.

**Pull request merged**
