### PR TITLE
Copy upload request to my space (#573)

### PR DESCRIPTION
**Pull request by imGok**
copyfromupload

### CODE REVIEW

**Comment by huynguyennovem** [comment]
Manual test:
After performing `Copy to My Space` action, the toast is shown but the list becomes empty

https://user-images.githubusercontent.com/29337364/132157175-d50874de-f3ee-4995-9944-ea6ee3884a24.mov

**Comment by huynguyennovem** [comment]
> * I know for empty list after copy, i'm refactoring the function list

go ahead!!

**Comment by huynguyennovem** [comment]
The commit message should follow the format, please!
Format: `LA-<ticket-number> <Commit-message>`

**Comment by imGok** [comment]
> The commit message should follow the format, please!

We've discussed about it on Signal and choose that (#ID) was better to trace, have you changed ur mind

**Review by huynguyennovem — APPROVED** [review]

**Comment by imGok** [comment]
> He has not fix the issue

the fix was on "search upload request PR" so I waited for it to be merged :D

**Comment by imGok** [comment]
@huynguyennovem @hoangdat it's fixed

**Review by huynguyennovem — APPROVED** [review]
/lgtm

**Pull request merged**
