### PR TITLE
Release v2.0.0-alpha01

### PR DESCRIPTION
**Pull request by hoangdat**
@huynguyennovem please help me review this PR.

### CODE REVIEW

**Comment by huynguyennovem** [comment]
Missing an upgrade version for Android

**Comment by hoangdat** [comment]
> Missing an upgrade version for Android

not get your point

**Comment by huynguyennovem** [comment]
> > Missing an upgrade version for Android
> 
> not get your point

It means that need to increase version code for Android

**Comment by hoangdat** [comment]
> > > Missing an upgrade version for Android
> > 
> > 
> > not get your point
> 
> It means that need to increase version code for Android

oh yes, for CD of Android, we need to config it directly on Bitrise

**Comment by hoangdat** [comment]
@huynguyennovem please let me know when you complete review

**Review by huynguyennovem — APPROVED** [review]

**Pull request merged**
