### PR TITLE
LA-614 Add Log to Interactors

### PR DESCRIPTION
**Pull request by imGok**

### CODE REVIEW

**Comment by hoangdat** [comment]
This logging option only visible on debug? Not visible on release? @imGok

**Comment by imGok** [comment]
> This logging option only visible on debug? Not visible on release? @imGok

still investigating on that because I didn't confirmed. Can't run in release mode on my PC atm

**Comment by hoangdat** [comment]
> > This logging option only visible on debug? Not visible on release? @imGok
> 
> still investigating on that because I didn't confirmed. Can't run in release mode on my PC atm

how about with `flutter run release`

**Comment by imGok** [comment]
> how about with `flutter run release`

yes I've tried this with simulator and it didn't work will try with real device

**Comment by hoangdat** [comment]
Please make your solution compare with `fimber`: https://pub.dev/packages/fimber and other librarys

**Pull request closed without merging**
